src/SortableContainer/index.js
This PR walks parents to find the actual drag handle instance. Without this, sorting won't work if a handle has any children (`e.target.sortableHandle` isn't always the actual handle). To reproduce, use this as a drag handle:
```js
render() { return <span><span>::</span></span>; }
```
Great library by the way!
=> Bugfix: Support drag handles with children

src/SortableContainer/index.js
when adding multiple classes with `classList.add` they must be like this `'foo', 'bar'` currently they are applied like this `'foo, bar'`. So this will fix this issue and will allow to add multiple classes. 
keep in mind that the space after the backtick is required.
=> Fix helperClass

src/SortableElement/index.js
When changing the disabled/enabled state of an existing element it wasn't updated and stayed dnd enabled/disabled as the first time it was created.
=> Fix changing disable property while receiving props

src/SortableContainer/index.js, src/utils.js
Only support's [margin collapsing](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing) if all items have the same margins.
[How to uncollapse margin for adjacent siblings](http://stackoverflow.com/questions/1828804/how-do-i-uncollapse-a-margin#answer-1828940)
[How to disable margin collapsing](http://stackoverflow.com/questions/19718634/how-to-disable-margin-collapsing#answer-19719427)
=> Bugfix: Add support handling `margin`s on scrollable items. (fixes #26)

src/utils.js
ReactDOMServer provides window, but not document, so it still breaks server rendering.
=> fix server side rendering with ReactDOMServer

src/utils.js
Update arrayMove util to return the copy of array, instead of mutating the passed one.
I suppose, it is a bad practice to mutate an existing array with this util, it can cause some unpredictable side-effects. It works fine for local react component state, but can cause errors, when using it outside of the local state (flux stores or redux store, for example) by mutating the passed array.
=> Update arrayMove util.

src/SortableElement/index.js
my collection name changes ( I keep the path to the parent in the collection name, eg 'grandparent:0:parent:5:children' )  and the parents themselves are sortable, as such their indexes can change.
I didn't want to bind a new closure for each `onSortEnd` because I have so many items.
Anyhow, one PR
=> support changable collection

src/utils.js
treat touchCancel event like touchEnd to un-mount cloned element from DOM. This should resolve #72
=> add touch cancel support for utils

src/SortableContainer/index.js
Just found a place where used `clearTimeout` instead of `clearInterval` which could cause some side-effects.
=> The proper way to clear interval

src/SortableContainer/index.js
This change fixes a hard-to-debug and reproduce issue in Chrome. In one window, I can't sort anything at all, either in my application or even on the GitHub pages site. In another Incognito window in the same version of Chrome, I can sort just fine. I think it is a timing issue related to the way `setTimeout` and the `setState` inside `handlePress` interact with each other. I tried eliminating the `setTimeout` when `pressDelay === 0` and the (alleged) timing issue went away.
=> Fix timing issue in Chrome

src/SortableContainer/index.js
Bottom line up front: Awesome plugin! Keep up the good work. — I’ve looked into a lot of similar components, and this is, by far the most stable, and the most easy to integrate component that I’ve seen so far. — Kudos for that.
**Summary**
This is for people with really sensitive touch devices (like trackpads configured to be really fast; or especially for designers who have gotten used to work fast and with precision.
**What was Happening**
(hard to describe verbally but I’ll try)
* The user starts moving her finger from outside the sortable list towards a sortable container.
* (while not stopping the finger movement on the trackpad) the user lightly touches the trackpad (in trackpad terms: this is a regular touch, not a force touch)
* (still not stopping the finger movement) the user …
=> Move cancel to the end of event queue

src/utils.js
Firefox has a fun bug, described here:
https://bugzilla.mozilla.org/show_bug.cgi?id=548397
window.getComputedStyle() returns null inside an iframe with display: none
This causes react-sortable-hoc to throw `TypeError: can't convert null to object`
The workaround is to return an array with a single fake mozilla-prefixed style in it if window.getComputedStyle() returns falsy.
=> fix: workaround for mozilla bug

src/SortableContainer/index.js
Height defined in getHelperDimensions() was not applied to the helper. This is fixed here. 
*please ignore wrong reference `getHelperStyle()` in commit message, this meant to be `getHelperDimensions()`.
=> Fix: Helper Height 

src/SortableContainer/index.js, src/SortableElement/index.js, src/utils.js
Fixes #114 
The lodash method accepts keys to omit as many arguments, `_.omit(obj, 'a', 'b', 'c')` or as an array `_.omit(obj, ['a', 'b', 'c'])`.  I've only supported the former as this project only implemented that usage.
I noticed there is no test rig.  I added the below snippet to `utils.js` and ran it with `babel-node` to test the util.  I also tested the storybook by hand and all seems well.
```js
const obj = { foo: 'foo', bar: 'bar', baz: 'baz' }
// No omitted keys
console.log(omit(obj))
//=> { foo: 'foo', bar: 'bar', baz: 'baz' }
// Some omitted keys
console.log(omit(obj, 'foo', 'bar'))
//=> { baz: 'baz' }
// All omitted keys
console.log(omit(obj, 'foo', 'bar', 'baz'))
//=> {}
// Omitted non-matching keys
console.log(omit(obj, 'not in there'))
//=> { foo: 'foo', bar: 'bar', baz: …
```
=> perf(lodash): use vanilla omit

src/SortableContainer/index.js
=> Fix inputs values.

src/.stories/Storybook.scss, src/.stories/index.js, src/SortableContainer/index.js, src/SortableElement/index.js
Here is a pull request for issue #112 
This commit has both a fix, and also a new story for nested lists as a test case.
=> fix: children elements in nested lists drag parent elements.

src/SortableContainer/index.js
Added the buttuon to `shouldCancelStart` to allow buttons to be clicked within SortableContainers.
See issue #136
=> Button will now be canceled in SortableContainer

src/SortableContainer/index.js
Because... trackpad ninjas.
https://twitter.com/Vjeux/status/840264657424146436
=> Default to `pointer-events: none` on Sortable helper

src/SortableContainer/index.js
Hey - great use of HOC here!  Really love it 👍 
'pressThreshold' found it's way into the WrappedComponent's props since it was implemented in 0.6.0.  Small tweak to remove it to prevent polluting. 
Cheers,
Ryan
=> Remove 'pressThreshold' prop from WrappedComponent

src/SortableContainer/index.js
Hi,
Currently, setting `visibility: hidden` on ghost element not guarantees its hiding. According to [spec](https://www.w3.org/TR/CSS22/visufx.html#visibility), descendants will be visible if they have `visibility: visible`. So additional `opacity: 0` should fix this.
=> Fix ghost element hiding

package.json, src/.stories/index.js, src/SortableContainer/index.js, src/SortableElement/index.js
See https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes
=> replace React.PropTypes with prop-types package to prevent warnings

src/Manager.js, src/SortableContainer/index.js
When the distance prop is set on a SortableContainer and a SortableElement is disabled, trying to move the element results in a "Cannot read property 'collection' of null" error being thrown.
This happens because when trying to sort a disabled element, the manager.active won't get set. In the SortableContainer's handleMove function, if distance is set, handlePress is executed even sorting was attempted on a disabled element.
=> Fixes "Cannot read property 'collection' of null" when distance set and a disabled element is moved

src/SortableContainer/index.js
The value of a file input can only be set to an empty string so we have to skip it.
=> Do not update value of cloned file inputs

README.md
It seems people frequently run into the issue that wrapper components consume certain props and it is the intended behavior as of #100 that those props are not passed down to the wrapped component. This fact should at least be documented.
=> Add doc for unfortunate prop consumption

src/SortableContainer/index.js
This pull requests updates the code to account for window scroll position. At the moment if the user scrolls the page while they are dragging an item, all the calculations are incorrect and you see the drag item jump position equivalent to how far you've scrolled. 
This makes adjustments to account for the window scroll position.
=> Fix drag when scrolling

src/SortableContainer/index.js
Added window.pageYOffset and window.pageXOffset to updatePosition and animateNode to allow proper drag and drop animation for Internet Explorer 11
=> IE 11 fixes for react-sortable-hoc

src/SortableContainer/index.js
This fixes #249
Jest serializes all props in snapshots. The current code sets window by default, which is a huge object. When Jest tries to serialize it, it typically throws `RangeError: Invalid string length` because the process runs out of memory. If you're lucky enough to actually get a test to pass, the snapshot will be around 250mb.
This switches from using defaultProps to setting the default ourselves, so in the test environment there won't be a prop value to serialize.
I confirmed the commonjs version fixes the issue. I'm not sure how to test the es6/umd versions. `npm test` passes.
=> Set contentWindow default ourselves to avoid Jest serialization

.eslintrc, examples/drag-handle.js, examples/infinite-list.js, examples/virtual-list.js, examples/virtual-table-columns.js
I also enforced single quotes in ESLint because they are being used consistently in the codebase and applied ESLint's autofix on the examples.
Resolves #218.
=> Add example for sorting react-virtualized table columns

README.md
Since the README file is quite long, not sure putting the sponsor link at the bottom makes sense. Reverts clauderic/react-sortable-hoc#276
=> Revert "Update Code Sponsor link position"

src/SortableContainer/index.js
Right now, even in the story book, this is broken on chrome, ff, & edge.
This just fixes it to not use document.body to set the scroll. There was also an issue with double computation in the  animateNodes function, where if the scrollcontainer was set to the parent, and we calculate both window and parent separately, it's a problem. So the key is to just use the scrollcontainer to SET the scroll value, and assume both window and container can scroll.
=> Fix for using window as scrolling container

src/SortableContainer/index.js
This PR fixes potential issues with calling `removeEventListeners` on `componentWillUnmount` if the `container` node has already unmounted
=> Fix issues with removeEventListener when container is undefined

src/SortableContainer/index.js, src/utils.js
This PR fixes issues with the `distance` prop and `pressThreshold` on mobile due to the fact that `event.pageX` is sometimes undefined
=> Fix issues with distance and pressThreshold props on mobile

src/SortableContainer/index.js, src/utils.js
This PR fixes an issue where scroll events would be cancelled on touch devices due to code aimed at fixing issues on desktop with anchor tags as sortable elements.
=> Fix scrolling issues on mobile with anchor tag elements

src/SortableContainer/index.js
I found an issue when you set a distance and you use `SortableHandle`.
After you click on the handle, you are able to drag the element from everywhere inside the `li`.
| Before        | After           |
| ------------- |:-------------:|
|![2018-11-20 19 39 58](https://user-images.githubusercontent.com/4728325/48811535-3cc11280-ecfc-11e8-87ea-4496b6426cfb.gif) | ![2018-11-20 19 42 48](https://user-images.githubusercontent.com/4728325/48811957-18fecc00-ecfe-11e8-87e5-64f2b935e862.gif) |
So the main problem comes from [here](https://github.com/clauderic/react-sortable-hoc/blob/master/src/SortableContainer/index.js#L179). During the handleStart we set the manager.
But inside the `handleEnd` we never unset the manager if the distance prop was set. You can check the code …
=> Fix a bug when you use SortableHandle and distance prop.

types/index.d.ts
This PR fixes the TypeScript types definition for the `helperContainer` prop. `1.5.0` introduced the ability to pass a function to the `helperContainer` prop, but the type definitions were not updated.
=> fix: update helperContainer prop type definition

src/SortableContainer/index.js
The `helperContainer` prop needs to be included in the list of omitted props when spreading props onto `WrappedComponent`. Otherwise, passing a DOM element string to `SortableContainer` will cause React to complain about the prop. Example:
```jsx
const SortableTBody = SortableContainer('tbody')
```
Using `<SortableTBody/>` will generate the following:
```
Warning: React does not recognize the `helperContainer` prop on a DOM element. [...]
```
Thanks for adding the `helperContainer` feature, it allowed me to simplify some of my code!
=> fix: omit helperContainer prop from WrappedComponent

src/SortableContainer/index.js
this merge resolves this issue:
#242
=> Auto scrolling is improved

src/SortableContainer/index.js
Same as with the `helperContainer` addition... the added prop needs to be explicitly omitted from those that are passed through.
I guess this repo would benefit from having automated tests. ;) To be clear, that's not meant as a criticism — I know we're all strapped for time and I could create a PR adding tests if I wanted to. I'm operating under the same constraint.
=> fix: omit disableAutoscroll prop

src/SortableContainer/index.js, src/utils.js
[Subissue of #501](https://github.com/clauderic/react-sortable-hoc/pull/501#discussion_r264287089)
This PR improves the scroll container default by checking the element's ancestors for appropriate scrolling styles. It also replaces references to `this.container` with those to `this.scrollContainer` in the autoscrolling logic.
This mainly impacts the nested list use case; other use cases (including window as scroll container) should remain unaffected.
If this gets merged in, I'll put up a commit in #501 to consolidate the changes.
_Sorry for the terrible GIF quality_
| Before | After |
|---|---|
| ![masterscroll](https://user-images.githubusercontent.com/46533681/54211581-f6184380-44b7-11e9-87ae-1c6f9ff57fda.gif) | ![sortingscroll](https://user-images.githubusercontent.com/46533681/54211601 …
=> Improve scroll container behaviour

src/SortableContainer/index.js
Hello, after installing the last release of the package I've encountered problem with sorting canvas items. After some debugging I found out that the problem is in copying canvas context on sort (it gets elements from array of items with the wrong index).
=> fixed cloning canvas context of dragged items

src/utils.js
This addresses a bug introduced in version 1.8.0 (https://github.com/clauderic/react-sortable-hoc/commit/43ad122) that currently occurs when a canvas element within a cloned node has no width or no height. When this happens, the following exception is thrown:
```
Uncaught (in promise) DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
```
To handle this, we simply check the width and height on every canvas element before copying its context over.
=> Don't copy canvas context if canvas has 0 dimension

package.json
`browser` field has a priority over `module` field in all bundlers. Adding it to package.json drops all goodness of esm bundle.
It should be used in a bit different way to support both node and browser fields.
https://github.com/uber/react-map-gl/blob/1da1398c063ffc3b8464744bde6781cb5dc3866e/package.json#L20-L24
=> Remove browser field with umd bundle

src/SortableContainer/index.js
This is the same issue as https://github.com/clauderic/react-sortable-hoc/issues/118 but it also applies to button on FF
Example of issue: https://84r5vjm2yl.codesandbox.io/ (FF only)
=> Fix firefox event issue related to Button tag

rollup.config.js
`npm run build` is currently broken, for two reasons:
* `browser` was removed from package.json recently (https://github.com/clauderic/react-sortable-hoc/commit/d3b30fd369a05c732200203d8b421758b6e12222), but it's used in rollup.config.js
* `minify && uglify` becomes `undefined` for the non-minified build, which makes `rollup-plugin-commonjs` throw this (at https://github.com/rollup/rollup-plugin-commonjs/blob/v9.3.4/src/resolve-id.js#L50), because `undefined` isn't a valid plugin:
```
[!] TypeError: Cannot read property 'resolveId' of undefined
TypeError: Cannot read property 'resolveId' of undefined
at .../react-sortable-hoc/node_modules/rollup-plugin-commonjs/src/resolve-id.js:52:6
```
(No idea why this wasn't always happening in the past :man_shrugging:)
This PR is a quick fix for …
=> fix: Fix broken UMD build

src/AutoScroller/index.js, src/SortableContainer/index.js
If `disableAutoscroll` is set to `true` by another event while user is dragging, scroll still continues.
Must also clear `autoScroller` when autoscroll gets disabled.
=> Clear autoscroller when autoscroll is disabled

src/.stories/Storybook.scss, src/.stories/index.js, src/SortableContainer/index.js, src/utils.js, types/index.d.ts
Based off of https://github.com/clauderic/react-sortable-hoc/pull/487
=> [Feature] CSS grid-gap support

package.json, src/SortableContainer/index.js, src/SortableElement/index.js, src/SortableHandle/index.js
Continued the work of @natew 
Also I moved the createContext call underneath all the import statements because my vscode was complaining about that.
=> Use new react context!

types/index.d.ts
fix #666
Solves the issue `disableAutoscroll` does not exist on type `SortableContainerProps`
=> fix: can't find key 'disableAutoscroll' in SortableContainerProps

src/SortableContainer/index.js
Fix https://github.com/clauderic/react-sortable-hoc/issues/751
Avoid issues on mobile where an error is triggered when calling
preventDefault on an event that cannot be cancelled.
Fix these kind of error messages:
> [Intervention] Ignored attempt to cancel a touchmove event with
cancelable=false, for example because scrolling is in progress and
cannot be interrupted.
https://developer.mozilla.org/en-US/docs/Web/API/Event/cancelable
=> fix: check if event is cancelable before calling preventDefault

src/SortableContainer/index.js
This PR is based off of https://github.com/clauderic/react-sortable-hoc/pull/532. Resolves #578, #440 and #9.
> I believe this addresses #440 and #9.
>
> The underlying issue with dragging on mobile seems to be related to this issue. This pull request implements this proposed solution, by simply listening to event.target if the event is a mobile event (ie event.touches).
>
> This works in my tests, but obviously open to discussion.
=> Fix touch events being lost by listening to event.target on mobile

src/SortableContainer/index.js
This PR fixes the issue that is happening in this demo (http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/grid?_k=8abqva)
and demonstrated in this issue #626 
The calculation that was made to determine if a node has moved past the right bounds is using `offset.width` which is only half of the width of the node. This means, if there are more than half of the width of empty space on the right of the container, the node will shift out of the Grid like the image above.
resolves #626, resolves #551, resolves #523, resolves #689
=> Fix shift to next row calculation
